services:
  dev-server:
    labels:
      # Enable Traefik to listen to this container over HTTP to port 5173
      - traefik.enable=true
      - traefik.http.routers.dev-server.rule=Host(`dev.home`)
      - traefik.http.routers.dev-server.priority=10
      - traefik.http.routers.dev-server.entrypoints=web
      - traefik.http.routers.dev-server.service=dev-server
      - traefik.http.services.dev-server.loadbalancer.server.port=5173
    image: tylergannon/svelte-dev:latest
    environment:
      VITE_ARGS: --force
    
    restart: always
    volumes:
      - "./:/TransitWeb"
      - dev_node_modules:/TransitWeb/node_modules/
      - pnpm_store:/opt/pnpm
    networks:
      - stack_network

volumes:
  dev_node_modules:
  pnpm_store:

networks:
  stack_network:
    external: true
    name: stack_default
