services:
  dev-server:
    image: tylergannon/svelte-dev:latest
    restart: always
    volumes:
      - "./:/app"
      - dev_node_modules:/app/node_modules
    environment:
      DATABASE_URL: mongodb://mongodb:27017/transitweb?ssl=false
    command:
    - "/etc/init_container.sh"
    - "--debug"
    - "--force"
    ports:
      - '5173:5173'
      - '15000:15000'
    depends_on:
      astroapi:
        condition: service_healthy
      mongodb:
        condition: service_healthy

  astroapi:
    image: tylergannon/astroapi:latest
    volumes:
      - astroapi_logs:/var/log
    environment:
      REDIS_URL: redis://redis
    ports:
      - '8080:80'
    depends_on:
      redis:
        condition: service_healthy

  mongodb:
    build: servers/mongo
    hostname: mongodb
    container_name: mongodb
    environment:
      MONGO_INITDB_DATABASE: transitweb
    volumes:
      - mongo_data:/data/db
      - mongo_configdata:/data/configdb
      - ./.out/mongodb-initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--maxmemory', '200mb', '--maxmemory-policy', 'volatile-lru']
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'set', 'HEALTHCHECK', '1']
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 40s

volumes:
  astroapi_logs:
  dev_node_modules:
  mongo_configdata:
  mongo_data:
  redis_data:
