services:
  astroapi:
    image: tylergannon/astroapi:latest
    volumes:
      - astroapi_logs:/var/log
    environment:
      REDIS_URL: redis://redis
    ports:
      - '8080:80'
    depends_on:
      redis:
        condition: service_healthy

  mongodb:
    build: servers/mongo
    hostname: mongodb
    container_name: mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--maxmemory', '200mb', '--maxmemory-policy', 'volatile-lru']
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'set', 'HEALTHCHECK', '1']
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 40s

volumes:
  astroapi_logs:
  mongo_data:
  redis_data:
