services:
  astroapi:
    image: tylergannon/astroapi:latest
    volumes:
      - astroapi_logs:/var/log
    environment:
      REDIS_URL: redis://redis
    ports:
      - "8080:80"
    depends_on:
      redis:
        condition: service_healthy
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: transitweb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "200mb", "--maxmemory-policy", "volatile-lru"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "set", "HEALTHCHECK", "1"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 40s

volumes:
  astroapi_logs:
  redis_data:
  postgres_data:
