services:
  astroapi:
    image: tylergannon/astroapi:latest
    volumes:
      - astroapi_logs:/var/log
    environment:
      REDIS_URL: redis://redis
    ports:
      - "8080:80"
    depends_on:
      redis:
        condition: service_healthy
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    # command: ["mongod", "--storageEngine", "wiredTiger", "--wiredTigerCacheSizeGB", "1"]
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 40s
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--maxmemory", "200mb", "--maxmemory-policy", "volatile-lru"]
    healthcheck:
      test: ["CMD", "redis-cli", "set", "HEALTHCHECK", "1"]
      interval: 5s
      timeout: 1s
      retries: 3
      start_period: 40s

volumes:
  astroapi_logs:

