FROM tylergannon/alpine-fish
ARG UID
ARG GID
ENV UID=${UID} GID=${GID}

RUN [ -z "$(grep :${GID}: /etc/group)" ] && addgroup -g $GID -S node; \
    adduser -u $UID -G node -s /bin/sh -h /home/node -D node \
    && apk add --no-cache \
        nodejs \
        npm \
    && mkdir -p /app/node_modules \
    && chown -R node:root /app


USER node

