---
- hosts: all
  name: Install Docker and other Apt/Snap Packages
  remote_user: root
  vars_files:
    - ../vars/main.yml
  vars:
    keychain_path: /etc/apt/keychains
    apt_repos:
      - name: Docker
        key_url: https://download.docker.com/linux/ubuntu/gpg
        file_name: docker_signing.key
        repo: https://download.docker.com/linux/ubuntu
        section: stable
        keyword: jammy
        options: ''
      - name: NGINX
        key_url: https://nginx.org/keys/nginx_signing.key
        file_name: nginx_signing.key
        repo: http://nginx.org/packages/mainline/ubuntu
        section: nginx
        keyword: jammy
        options: ''
      - name: MongoDB
        key_url: https://www.mongodb.org/static/pgp/server-6.0.asc
        file_name: mongodb_signing.key
        repo: https://repo.mongodb.org/apt/ubuntu
        section: multiverse
        keyword: jammy/mongodb-org/6.0
        options: arch=amd64,arm64
  tasks:
    - name: Ensure keychain directory exists
      ansible.builtin.file:
        path: "{{ keychain_path }}"
        state: directory
        mode: '0755'
        owner: root
    - name: Add keys and repos
      ansible.builtin.include_tasks: blocks/add_repo.yml
      loop: "{{ apt_repos }}"

    - name: Install apt-get dependencies
      ansible.builtin.apt:
        name: "{{ system.apt_packages }}"
        state: present
        update_cache: true

    - name: Service should be running - {{ item }}
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - docker
        - nginx
        - mongod

    - name: Install snap packages
      community.general.snap:
        name: "{{ item }}"
        state: present
        classic: true
      loop: "{{ system.classic_snap_packages }}"
