---
- hosts: all
  name: Configure Firewall
  remote_user: root
  vars:
    username: "{{ lookup('env', 'USER') }}"

  tasks:
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH
    - name: UFW - Allow HTTP connections
      community.general.ufw:
        rule: allow
        port: '80'
    - name: UFW - Allow HTTPS connections
      community.general.ufw:
        rule: allow
        port: '443'
    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
