---
- hosts: all
  name: Change user shell.
  vars_files:
    - ../vars/main.yml
  remote_user: "{{ user.name }}"
  become: true
  tasks:
    - name: Add fish to /etc/shells
      ansible.builtin.lineinfile:
        path: /etc/shells
        state: present
        search_string: "{{ homebrew.bin }}/fish"
        line: "{{ homebrew.bin }}/fish"

    - name: Change user's shell to fish.
      ansible.builtin.user:
        name: "{{ user.name }}"
        shell: "{{ homebrew.bin }}/fish"
