---
- hosts: all
  name: Install LunarVim
  vars:
    username: "{{ lookup('env', 'USER') }}"
    homebrew_bin: "/home/linuxbrew/.linuxbrew/bin"
  remote_user: "{{ username }}"
  tasks:
    - name: Install npm neovim.
      community.general.npm:
        name: neovim
        global: true
    - name: Install pip packages.
      ansible.builtin.pip:
        name:
          - pynvim
          - neovim-remote
        executable: pip3
    - name: Install Homebrew packages.
      community.general.homebrew:
        name:
          - luajit
    - name: Install Cargo dependencies.
      community.general.cargo:
        name:
          - fd-find
          - ripgrep
    - name: Download the LunarVim installer.
      ansible.builtin.get_url:
        url: https://tinyurl.com/lunarvim-stable-12
        dest: "/home/{{ username }}/lvim_install.sh"
        mode: '0755'
    - name: Install LunarVim.
      ansible.builtin.command: ~/lvim_install.sh -y --overwrite --no-install-dependencies
      args:
        creates: "/home/{{ username }}/.local/bin/lvim"
      environment:
        LV_BRANCH: release-1.2/neovim-0.8
    - name: Remove the LunarVim installer.
      ansible.builtin.file:
        path: "/home/{{ username }}/lvim_install.sh"
        state: absent
    - name: Alias to lvim in fish conf
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.config/fish/config.fish"
        line: "alias lvim='~/.local/bin/lvim'"
        state: present
    - name: Add fish vi keybindings to fish
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.config/fish/config.fish"
        line: "fish_vi_key_bindings"
        state: present
    - name: Add Starship
      ansible.builtin.lineinfile:
        path: "/home/{{ username }}/.config/fish/config.fish"
        line: "starship init fish | source"
        state: present
