- hosts: all
  name: Clone Repo
  vars_files:
    - ../vars/main.yml
  remote_user: "{{ user.name }}"
  tasks:
    - name: Ensure src directory exists.
      ansible.builtin.file:
        path: /home/{{ user.name }}/src
        state: directory
        mode: '0755'
    - name: Clone repo
      ansible.builtin.command:
        cmd: gh repo clone {{ item }}
        creates: /home/{{ user.name }}/src/{{ item.split('/', 1)[1] }}
        chdir: /home/{{ user.name }}/src
      loop: "{{ repositories }}"
      environment:
        GITHUB_TOKEN: "{{ user.github_token }}"
