---
- hosts: all
  name: Install LunarVim
  vars_files:
    - ../vars/main.yml
    - ../vars/nginx.yml
  # We want nginx configured to use the correct pid file and run location.
  # Let's start by creating the nginx user.
  tasks:
    - name: Create nginx group
      ansible.builtin.group:
        name: nginx
        state: present
    - name: Create nginx user
      ansible.builtin.user:
        name: nginx
        system: true
        group: nginx
        shell: /usr/sbin/nologin
        state: present
