---
- hosts: all
  name: Install Homebrew on Ubuntu 20.04
  vars_files:
    - ../vars/main.yml
    - ../vars/homebrew.yml
  remote_user: "{{ user.name }}"
  tasks:
    - name: If brew command can't be found, run shell command to install Homebrew.
      ansible.builtin.shell: >
        NONINTERACTIVE=true /bin/bash -c "$(curl -fsSL {{ homebrew.install_url }})"
      args:
        creates: /home/linuxbrew/.linuxbrew
      # When the directory /home/linuxbrew/.linuxbrew/bin exists, the installation is unnecessary.
    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ homebrew.packages }}"
