---
- hosts: all
  name: Install Certbot
  vars_files:
    - ../vars/main.yml
  remote_user: '{{ user.name }}'
  become: true
  vars:
    snap_tstamp: /etc/snap_updated
  tasks:
    - name: Install core snap package.
      community.general.snap:
        name: core
    - name: Find whether snap was updated today.
      ansible.builtin.find:
        paths: /etc
        patterns: snap_updated
        age: -15d
      register: find_snap_updated
    - name: Remove snap_updated file find_snap_updated is empty.
      ansible.builtin.file:
        path: /etc/snap_updated
        state: absent
      when: find_snap_updated.matched == 0
    - name: Run snap refresh core.
      ansible.builtin.shell: >
        snap refresh &> /dev/null;
        and echo "{{ ansible_date_time.date }}" > /etc/snap_updated;
      args:
        executable: '{{ fish.exe }}'
        creates: /etc/snap_updated
    - name: Install Snap Packages, including Certbot
      community.general.snap:
        name: '{{ system.classic_snap_packages }}'
        classic: true
    - name: Add link to Certbot binary
      ansible.builtin.file:
        src: /snap/bin/certbot
        dest: /usr/bin/certbot
        state: link
