---
- hosts: all
  name: Prepare for nginx conf
  vars_files:
    - ../vars/main.yml
    - ../vars/nginx.yml
  remote_user: '{{ user.name }}'
  become: true
  tasks:
    - name: Ensure dhparam.pem exists.
      ansible.builtin.command: openssl dhparam -out /etc/nginx/dhparam.pem 2048
      args:
        creates: /etc/nginx/dhparam.pem
    - name: Ensure letsencrypt dir exists.
      ansible.builtin.file:
        path: /var/www/_letsencrypt
        owner: root
        group: nginx
        mode: '0750'
        state: directory
    - name: Ensure www directories exist.
      ansible.builtin.file:
        path: '/var/www/{{ item }}'
        owner: root
        group: nginx
        mode: '0750'
        state: directory
      loop: '{{ site.hostnames }}'
    - name: 'Create SSL Certificates'
      ansible.builtin.include_tasks:
        file: blocks/certbot_key.yml
      loop: '{{ site.hostnames }}'
