---
- name: Archive old configuration

- name: Unzip configuration dir.
  ansible.builtin.unarchive:
    src: "{{ site.cfg }}"
    dest: "/etc/nginx"
    owner: root
    mode: '0644'

- name: Restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
